steps:
  # フロントエンドのビルドとデプロイ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '-t', 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}',
           '--build-arg', 'VITE_BACKEND_URL=${_VITE_BACKEND_URL}',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_FRONTEND_SERVICE}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

  # バックエンドサーバーのビルドとデプロイ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t', 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}',
           '--build-arg', 'VERTEX_PROJECT_ID=$PROJECT_ID',
           '--build-arg', 'VERTEX_LOCATION=${_REGION}',
           '--build-arg', 'VERTEX_MODEL_NAME=${_VERTEX_MODEL}',
           '--build-arg', 'CORS_ORIGINS=${_CORS_ORIGINS}',
           '-f', 'Dockerfile.server',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_BACKEND_SERVICE}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'VERTEX_PROJECT_ID=$PROJECT_ID,VERTEX_LOCATION=${_REGION},VERTEX_MODEL_NAME=${_VERTEX_MODEL},CORS_ORIGINS=${_CORS_ORIGINS}'

# ビルド時に必要な変数のみをCloud Buildで管理
substitutions:
  _REGION: asia-northeast1
  _FRONTEND_SERVICE: kawaii-chat
  _BACKEND_SERVICE: practice-app-server
  _VITE_BACKEND_URL: https://practice-app-server-979841275453.asia-northeast1.run.app
  _VERTEX_MODEL: gemini-pro
  _CORS_ORIGINS: https://kawaii-chat-979841275453.asia-northeast1.run.app

images:
  - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}'
  - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}'

options:
  logging: CLOUD_LOGGING_ONLY 